print(" *** ID card ****")
id, f_name, n_name = input("Enter your student_ID firstname nickname : ").split(' ')
print(f"----------------------------------")
print(f"| »-(¯`·.·´¯)->CARD<-(¯`·.·´¯)-« |")
print(f"|                                |")
print(f"| {f_name:15}{id:>15} |")
print(f"|{n_name:^32s}|")
print(f"|                                |")
print(f"| (-.-)Zzz....           (╯︵╰,) |")
print(f"----------------------------------")